# Generated by Django 4.2.1 on 2023-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='test2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='test3', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='yaxshi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.CharField(default='krill', max_length=30),
            preserve_default=False,
        ),
    ]
