# Generated by Django 4.2.1 on 2023-05-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_language_book_langs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='langs',
            new_name='language',
        ),
    ]
