# Generated by Django 4.2.1 on 2023-05-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_langs_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication',
            new_name='year_of_publication',
        ),
    ]
