# Generated by Django 4.2.1 on 2023-05-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_publication_book_year_of_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
